{{- if .Values.arangodb.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.arangodb.name }}-ingress
spec:
  rules:
    - host: {{ .Values.arangodb.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.arangodb.name }}
              servicePort: 8529
  tls:
    - hosts:
        - {{ .Values.arangodb.ingress.domain }}
      secretName: {{ .Values.ingressSecretName }}
{{- end }}