apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.collectors.gobmp.name }}"
spec:
  replicas: {{ .Values.collectors.gobmp.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.collectors.gobmp.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.collectors.gobmp.name }}"
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --kafka-server
          - {{ .Values.kafka.fullnameOverride }}.{{ .Release.Namespace }}:9092
          image: "{{ .Values.collectors.gobmp.image }}"
          imagePullPolicy: Always
          name: gobmp
          ports:
          - containerPort: 5000
            protocol: TCP
            name: incbmpsess
          - containerPort: 56767
            protocol: TCP
            name: perfmon
          {{- if .Values.collectors.gobmp.resources }}
          resources:
            {{- if .Values.collectors.gobmp.resources.requests }}
            requests:
              memory: {{ .Values.collectors.gobmp.resources.requests.memory | default "50Mi" | quote }}
              cpu: {{ .Values.collectors.gobmp.resources.requests.cpu | default "10m" | quote }}
            {{- else}}
            requests:
              memory: "50Mi"
              cpu: "10m"
            {{- end}}
            {{- if .Values.collectors.gobmp.resources.limits }}
            limits:
              memory: {{ .Values.collectors.gobmp.resources.limits.memory | default "1024Mi" | quote }}
              cpu: {{ .Values.collectors.gobmp.resources.limits.cpu | default "1" | quote }}
            {{- else}}
            limits:
              memory: "1024Mi"
              cpu: "1"
            {{- end }}
          {{- else }}
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Values.collectors.gobmp.name }}-config"