apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.collectors.telegrafIngress.name }}"
spec:
  type: NodePort
  ports:
  - name: 57400-tcp
    port: 57400
    nodePort: {{ .Values.collectors.telegrafIngress.nodePort }}
    targetPort: 57400
  selector:
    app: "{{ .Values.collectors.telegrafIngress.name }}"