apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.processors.topology.name }}-secret"
type: Opaque
data:
    .username: {{ .Values.arangodb.databaseUser | b64enc }}
    .password: {{ .Values.arangodb.databasePassword | b64enc }}